// Generated from Universal Agent Studio JSON Schema v0.1.0.
// Do not edit manually; run `pnpm generate:contracts`.

import type { NodeSpec } from "./node-spec.generated.js";
export type { NodeSpec } from "./node-spec.generated.js";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ApiKeyCreateView = ApiKeyView & {
  secret: string;
  [k: string]: unknown;
};
export type WebhookCreateView = WebhookView & {
  secret: string;
  [k: string]: unknown;
};

export interface ContractBundle {
  agent_draft?: AgentDraft;
  agent_spec?: AgentSpec;
  agent_version?: AgentVersion;
  api_key_create_request?: ApiKeyCreateRequest;
  api_key_create_view?: ApiKeyCreateView;
  error_envelope?: ErrorEnvelope;
  interface_schema?: InterfaceSchema;
  model_profile?: ModelProfile;
  node_spec?: NodeSpec;
  public_agent?: PublicAgentView;
  public_run?: PublicRunView;
  public_run_create_request?: PublicRunCreateRequest;
  public_run_event?: PublicRunEvent;
  publication?: PublicationState;
  publish_request?: PublishRequest;
  rollback_request?: RollbackRequest;
  run_event?: RunEvent;
  run_request?: RunRequest;
  run_trace?: RunTrace;
  tool_manifest?: ToolManifest;
  webhook_create_request?: WebhookCreateRequest;
  webhook_create_view?: WebhookCreateView;
}
export interface AgentDraft {
  agent_id: string;
  agent_spec: AgentSpec;
  base_version_id: string;
  digest: string;
  draft_id: string;
  layout: Layout;
  revision: number;
  schema_version: "0.1.0";
  updated_at: string;
}
export interface AgentSpec {
  agent_id: string;
  edges: Edge[];
  extensions: Extensions;
  interface: InterfaceSchema;
  localized_metadata: LocalizedMetadata;
  model_profiles: ModelProfile[];
  /**
   * @minItems 1
   */
  nodes: [NodeSpec, ...NodeSpec[]];
  policies: PolicySet;
  revision: number;
  schema_version: "0.1.0";
  tools: ToolManifest[];
}
export interface Edge {
  id: string;
  source: Endpoint;
  target: Endpoint;
}
export interface Endpoint {
  node_id: string;
  port_id: string;
}
export interface Extensions {
  [k: string]: {
    [k: string]: unknown;
  };
}
export interface InterfaceSchema {
  default_locale: "ru-RU" | "en-US";
  input_fields: InputField[];
  /**
   * @minItems 2
   */
  locales: ["ru-RU" | "en-US", "ru-RU" | "en-US", ...("ru-RU" | "en-US")[]];
  mode: "form" | "chat" | "hybrid";
  result_schema: {
    [k: string]: unknown;
  };
}
export interface InputField {
  id: string;
  label: LocalizedText;
  required: boolean;
  schema: {
    [k: string]: unknown;
  };
}
export interface LocalizedText {
  "en-US": string;
  "ru-RU": string;
}
export interface LocalizedMetadata {
  description: LocalizedText;
  name: LocalizedText;
}
export interface ModelProfile {
  data_policy: DataPolicy;
  extensions: Extensions;
  id: string;
  localized_metadata: LocalizedMetadata;
  parameters: Parameters;
  required_capabilities: ("text" | "structured_output" | "tool_calling" | "vision" | "embeddings")[];
  /**
   * @minItems 1
   */
  routes: [Route, ...Route[]];
}
export interface DataPolicy {
  external_allowed: boolean;
  regions: string[];
  retention_policy: "none" | "provider-default" | "contractual-zero-retention";
  sensitive_data_allowed: boolean;
}
export interface Parameters {
  max_output_tokens: number;
  temperature: number;
}
export interface Route {
  adapter: string;
  credential_ref?: string;
  model: string;
}
export interface PolicySet {
  data_classification: "public" | "internal" | "confidential" | "restricted";
  redaction_policy_id: string;
  retention_policy_id: string;
}
export interface ToolManifest {
  adapter: {
    ref: string;
    type: "builtin" | "http" | "openapi" | "mcp" | "sandbox";
  };
  approval_policy: "never" | "configurable" | "required";
  credential_refs: CredentialReference[];
  extensions: Extensions;
  id: string;
  idempotency: {
    key_strategy: "not-applicable" | "run-and-node" | "caller-provided";
    required: boolean;
  };
  input_schema: {
    [k: string]: unknown;
  };
  localized_metadata: LocalizedMetadata;
  output_schema: {
    [k: string]: unknown;
  };
  permissions: string[];
  side_effect: "none" | "read" | "write" | "destructive";
  version: string;
}
export interface CredentialReference {
  credential_ref: string;
}
export interface Layout {
  /**
   * @maxItems 256
   */
  nodes: Position[];
  viewport: Viewport;
}
export interface Position {
  node_id: string;
  x: number;
  y: number;
}
export interface Viewport {
  x: number;
  y: number;
  zoom: number;
}
export interface AgentVersion {
  agent_id: string;
  agent_spec: AgentSpec;
  agent_spec_digest: string;
  created_at: string;
  dependency_lock: Dependency[];
  schema_version: "0.1.0";
  signature?: Signature;
  status: "published";
  version_id: string;
  version_number: number;
}
export interface Dependency {
  digest: string;
  id: string;
  kind: "model_adapter" | "tool" | "asset" | "capability_pack";
  version: string;
}
export interface Signature {
  algorithm: "ed25519";
  key_id: string;
  value: string;
}
export interface ApiKeyCreateRequest {
  expires_at: string | null;
  label: string;
  /**
   * @minItems 1
   */
  scopes: ["runs:create" | "runs:read" | "events:read", ...("runs:create" | "runs:read" | "events:read")[]];
}
export interface ApiKeyView {
  created_at: string;
  expires_at: string | null;
  key_id: string;
  label: string;
  last_used_at: string | null;
  prefix: string;
  revoked_at: string | null;
  /**
   * @minItems 1
   */
  scopes: ["runs:create" | "runs:read" | "events:read", ...("runs:create" | "runs:read" | "events:read")[]];
}
export interface ErrorEnvelope {
  code: string;
  details: {
    [k: string]: unknown;
  };
  message_key: string;
  node_id?: string;
  retryable: boolean;
}
export interface PublicAgentView {
  agent_id: string;
  agent_version_digest: string;
  agent_version_id: string;
  interface: InterfaceSchema;
  localized_metadata: LocalizedMetadata;
  schema_version: "0.1.0";
}
export interface PublicRunView {
  agent_id: string;
  agent_version_digest: string;
  agent_version_id: string;
  error_code: ("invocation_unavailable" | "run_cancelled") | null;
  events_url: string;
  locale: "ru-RU" | "en-US";
  output: {
    [k: string]: unknown;
  } | null;
  run_capability?: string;
  run_id: string;
  schema_version: "0.1.0";
  status: "queued" | "running" | "completed" | "failed" | "cancelled";
  status_url: string;
}
export interface PublicRunCreateRequest {
  input: {
    [k: string]: unknown;
  };
  locale: "ru-RU" | "en-US";
}
export interface PublicRunEvent {
  error_code: ("invocation_unavailable" | "run_cancelled") | null;
  occurred_at: string;
  output: {
    [k: string]: unknown;
  } | null;
  schema_version: "0.1.0";
  sequence: number;
  status: "queued" | "running" | "completed" | "failed" | "cancelled";
  type: "run.queued" | "run.started" | "run.progress" | "run.completed" | "run.failed" | "run.cancelled";
}
export interface PublicationState {
  active_version_id: string | null;
  agent_id: string;
  api_keys: ApiKeyView[];
  draft_digest: string;
  draft_revision: number;
  events: PublicationEventView[];
  schema_version: "0.1.0";
  versions: PublishedVersionView[];
  webhooks: WebhookView[];
}
export interface PublicationEventView {
  created_at: string;
  event_id: string;
  event_type: "publish" | "rollback";
  previous_version_id: string | null;
  selected_version_digest: string;
  selected_version_id: string;
}
export interface PublishedVersionView {
  created_at: string;
  digest: string;
  version_id: string;
  version_number: number;
}
export interface WebhookView {
  created_at: string;
  /**
   * @minItems 1
   */
  events: ["run.completed" | "run.failed" | "run.cancelled", ...("run.completed" | "run.failed" | "run.cancelled")[]];
  label: string;
  revoked_at: string | null;
  subscription_id: string;
  target_url: string;
}
export interface PublishRequest {
  expected_active_version_id: string | null;
  expected_draft_revision: number;
}
export interface RollbackRequest {
  expected_active_version_id: string;
  target_version_id: string;
}
export interface RunEvent {
  causation_id: string;
  correlation_id: string;
  error?: ErrorEnvelope;
  event_id: string;
  node_id?: string;
  occurred_at: string;
  payload: {
    [k: string]: unknown;
  };
  redaction_policy_id: string;
  run_id: string;
  schema_version: "0.1.0";
  sequence: number;
  type:
    | "run.started"
    | "node.started"
    | "model.requested"
    | "model.completed"
    | "tool.requested"
    | "tool.completed"
    | "approval.required"
    | "approval.resolved"
    | "node.failed"
    | "node.completed"
    | "run.completed"
    | "run.failed"
    | "run.cancelled";
}
export interface RunRequest {
  agent_version_digest: string;
  agent_version_id: string;
  idempotency_key: string;
  input: {
    [k: string]: unknown;
  };
  locale: "ru-RU" | "en-US";
  request_id: string;
  schema_version: "0.1.0";
  session_id?: string;
}
export interface RunTrace {
  agent_version_digest: string;
  agent_version_id: string;
  completed_at: string;
  error?: ErrorEnvelope;
  /**
   * @minItems 2
   */
  events: [RunEvent, RunEvent, ...RunEvent[]];
  input: {
    [k: string]: unknown;
  };
  metrics: Metrics;
  node_executions: NodeExecution[];
  output: {
    [k: string]: unknown;
  };
  provenance: Provenance;
  request_id: string;
  run_id: string;
  schema_version: "0.1.0";
  started_at: string;
  status: "completed" | "failed" | "cancelled";
}
export interface Metrics {
  cost: {
    amount: number;
    currency: string;
  };
  duration_ms: number;
  input_tokens: number;
  output_tokens: number;
  tool_calls: number;
}
export interface NodeExecution {
  attempt: number;
  completed_at: string;
  duration_ms: number;
  error?: ErrorEnvelope;
  input: {
    [k: string]: unknown;
  };
  node_id: string;
  output: {
    [k: string]: unknown;
  };
  started_at: string;
  status: "completed" | "failed" | "cancelled";
}
export interface Provenance {
  model_resolutions: ModelResolution[];
  redaction_policy_id: string;
  tool_resolutions: ToolResolution[];
}
export interface ModelResolution {
  adapter: string;
  model: string;
  parameters: {
    [k: string]: unknown;
  };
  profile_id: string;
  prompt_digest: string;
}
export interface ToolResolution {
  digest: string;
  tool_id: string;
  version: string;
}
export interface WebhookCreateRequest {
  /**
   * @minItems 1
   */
  events: ["run.completed" | "run.failed" | "run.cancelled", ...("run.completed" | "run.failed" | "run.cancelled")[]];
  label: string;
  target_url: string;
}
