// Generated from Universal Agent Studio JSON Schema v0.1.0.
// Do not edit manually; run `pnpm generate:contracts`.
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NodeSpec = {
  [k: string]: unknown;
} & {
  id: string;
  kind: "input" | "model" | "tool" | "output";
  type: string;
  version: string;
  localized_metadata: LocalizedMetadata;
  config: {
    [k: string]: unknown;
  };
  input_ports: Port[];
  output_ports: Port[];
  model_profile_ref?: string;
  tool_ref?: string;
  timeout_ms: number;
  retry_policy: RetryPolicy;
  extensions: Extensions;
};

export interface LocalizedMetadata {
  name: LocalizedText;
  description: LocalizedText;
}
export interface LocalizedText {
  "ru-RU": string;
  "en-US": string;
}
export interface Port {
  id: string;
  schema: {
    [k: string]: unknown;
  };
}
export interface RetryPolicy {
  max_attempts: number;
  backoff: "none" | "fixed" | "exponential";
}
export interface Extensions {
  [k: string]: {
    [k: string]: unknown;
  };
}
